const keywordLabels ={
gomlek:'gömlek',
hirka:'hırka',
suveter:'süveter',
tisort:'tişört',
bustiyer:'büstiyer',
esofman:'eşofman',
sort:'şort',
pardosu:'pardösü',
trenckot:'trençkot',
sabahlik:'sabahlık',
sutyen:'sütyen',
kulot:'külot',
canta:'çanta',
cuzdan:'cüzdan',
portfoy:'portföy',
kartlik:'kartlık',
sal:'şal',
atki:'atkı',
yuzuk:'yüzük',
kupe:'küpe',
bros:'broş',
corap:'çorap',
sapka:'şapka',
ayakkabi:'ayakkabı',
cizme:'çizme',
sapka:'şapka',
}

export default keywordLabels