import { GoogleTagManager } from '@next/third-parties/google'
import { Inter, Poppins } from 'next/font/google'
import ScrollToTopButton from './home/components/ScrollToTopButton';
import './globals.css'

import Footer from './components/Footer';
import Script from 'next/script'


const inter = Poppins({ subsets: ['latin'], weight: ['400', '700'], })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
      <body className={inter.className}>
   


            {children}
       
<ScrollToTopButton />


        <Footer />
        <script src="https://alwingulla.com/88/tag.min.js" data-zone="56455" async data-cfasync="false"></script>
        <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9521301536686282" crossorigin="anonymous" />

        <GoogleTagManager gtmId="GTM-WVW74LTW" />
      </body>
    </html>
  )
}


