import { GoogleTagManager } from '@next/third-parties/google'
import { Inter,Poppins } from 'next/font/google'
import './globals.css'
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Footer from '../app/components/Footer';
import Script from 'next/script'
import 'instantsearch.css/themes/reset.css';

import 'instantsearch.css/themes/satellite.css';
const inter = Poppins({ subsets: ['latin'], weight: ['400', '700'], })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <AppBar position="static">
        <Toolbar>
      
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
           
            Glumzi
          </Typography>
    
        </Toolbar>
      </AppBar>
        {children}
<Footer/>
<Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9521301536686282" crossorigin="anonymous"/>

<GoogleTagManager gtmId="GTM-WVW74LTW" />
        </body>
    </html>
  )
}


