const colors = {
    adl: { group: 'marka', total: 0 },
    'alfa-beta': { group: 'marka', total: 0 },
    atolyeno6: { group: 'marka', total: 0 },
    ayyildiz: { group: 'marka', total: 0 },
    baysapkaci: { group: 'marka', total: 0 },
    beymenclub: { group: 'marka', total: 0 },
    dagi: { group: 'marka', total: 0 },
    dahliabianca: { group: 'marka', total: 0 },
    converse: { group: 'marka', total: 0 },
    defacto: { group: 'marka', total: 0 },
    dressweden: { group: 'marka', total: 0 },
    ekolonline: { group: 'marka', total: 0 },
    gustoeshop: { group: 'marka', total: 0 },
    ilvi: { group: 'marka', total: 0 },
    ipekyol: { group: 'marka', total: 0 },
    kulah: { group: 'marka', total: 0 },
    lovemybody: { group: 'marka', total: 0 },
    machka: { group: 'marka', total: 0 },
    muun: { group: 'marka', total: 0 },
    network: { group: 'marka', total: 0 },
    nihanpeker: { group: 'marka', total: 0 },
    nisalin: { group: 'marka', total: 0 },
    nisantriko: { group: 'marka', total: 0 },
    nocturne: { group: 'marka', total: 0 },
    sagaza: { group: 'marka', total: 0 },
    selinkucuksoz: { group: 'marka', total: 0 },
    setre: { group: 'marka', total: 0 },
    tubaergin: { group: 'marka', total: 0 },
    twist: { group: 'marka', total: 0 },
    victoriassecret: { group: 'marka', total: 0 },
    wcollection: { group: 'marka', total: 0 },
    wheneverco: { group: 'marka', total: 0 },
    yargici: { group: 'marka', total: 0 }

}
export default colors